### ISSUE TITLE
simulatedHub.js TypeError: callback is not a function

### ISSUE THREAD

**Issue by benhalverson** [noopkat/electric-io#104]
I found the simulatedDeviceList.js that shows the sample method names
for example 
```
  'AZ3166': {
    interval: 1000,
    properties: [
      {name: 'temperature', minmax: [0, 40]},
      {name: 'humidity', minmax: [0, 100]}
    ]
  }
```
Steps to reproduce
1. change SIMULATING from false to true
2. npm start
3. browse to localhost:3000
4. click edit on the button card select AZ3166 and add method name humidity
5. press save and press the button 
6. observe the server log

expected results
no 500 errors

```
TypeError: callback is not a function
    at Object.Client.invokeDeviceMethod [as callDeviceMethod] (/Users/benhalverson/projects/electric-io/lib/simulator/simulatedHub.js:12:10)
    at /Users/benhalverson/projects/electric-io/lib/routes.js:58:16
    at Layer.handle [as handle_request] (/Users/benhalverson/projects/electric-io/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/benhalverson/projects/electric-io/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/benhalverson/projects/electric-io/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/benhalverson/projects/electric-io/node_modules/express/lib/router/layer.js:95:5)
    at /Users/benhalverson/projects/electric-io/node_modules/express/lib/router/index.js:281:22
    at param (/Users/benhalverson/projects/electric-io/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/benhalverson/projects/electric-io/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/benhalverson/projects/electric-io/node_modules/express/lib/router/index.js:365:14)
```

**Comment by noopkat** [comment]
thanks for reporting! This is fixed in #95 and waiting to go out once I've written a test 😄
