### ISSUE TITLE
Cards cannot be dismissed

### ISSUE THREAD

**Issue by escherina** [noopkat/electric-io#110]
I get the following error when trying to dismiss a card (by clicking the `X`):

```
DOMException: Failed to execute 'showModal' on 'HTMLDialogElement': The element is not in a Document.
    at t.show (http://localhost:3000/js/dist/vendors~main.bundle.js:14:260550)
    at openCardDeleteModal (http://localhost:3000/js/dist/main.bundle.js:1:18476)
    at click (http://localhost:3000/js/dist/main.bundle.js:1:6439)
    at $e (http://localhost:3000/js/dist/vendors~main.bundle.js:7:11091)
    at HTMLButtonElement.n (http://localhost:3000/js/dist/vendors~main.bundle.js:7:12796)
    at HTMLButtonElement.i._wrapper (http://localhost:3000/js/dist/vendors~main.bundle.js:7:47334)
```

Possibly related to this issue on `vue-a11y-dialog`: https://github.com/morkro/vue-a11y-dialog/issues/8

**Comment by escherina** [comment]
Update: it does work on the Cool Button card in my dashboard (which is copied from the default dashboard) - but on no other card, so I think it's likely to be caused by the issue I linked above.

**Comment by escherina** [comment]
Note: this seems to be fixed by updating `vue-a11y-dialog` as in @kleinfreund 's latest PR #111.

**Comment by kleinfreund** [comment]
Ah, I wondered if that would *auto-magically* fix it. We got lucky. :)

**Comment by noopkat** [comment]
thanks @escherina for reporting this 💯 
thanks @kleinfreund for fixing this with your diligent dependency updating! 🥇 

![bitmoji](https://render.bitstrips.com/v2/cpanel/86b2f3e6-fe1f-4607-b99c-e50f5d258b27-8016a622-e09b-4505-8856-7726a074b1f9-v1.png?transparent=1&palette=1&width=246)
